name: calendar-sync-deploy

services:
  postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: calendar-sync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  server:
    image: ghcr.io/yvan2xero/calendarsync-server:latest
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:password@postgres:5432/calendar-sync}
      PORT: ${PORT:-3000}
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped

  worker:
    image: ghcr.io/yvan2xero/calendarsync-worker:latest
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:password@postgres:5432/calendar-sync}
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      server:
        condition: service_started
    restart: unless-stopped

  cron:
    image: ghcr.io/yvan2xero/calendarsync-cron:latest
    environment:
      CRON_SECRET: ${CRON_SECRET}
      CRON_BASE_URL: ${CRON_BASE_URL:-http://server:3000}
      CRON_INTERVAL: ${CRON_INTERVAL:-600}
    depends_on:
      server:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
    name: calendar-sync_postgres_data
