name: calendar-sync

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: calendar-sync-postgres
    environment:
      POSTGRES_DB: calendar-sync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "54322:5432"
    volumes:
      - calendar-sync_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  calendar-sync_postgres_data:
